FROM rocm/dev-ubuntu-22.04:6.1

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    cmake \
    git \
    ninja-build \
    python3 \
    python3-pip \
    ocl-icd-opencl-dev \
    clinfo \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/OpenPhotogrammetry

COPY . /workspace/OpenPhotogrammetry

RUN pip3 install --no-cache-dir pyopf requests OpenImageIO

CMD ["bash"]
